/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ExchangeProxy, ExchangeProxyInterface } from "../ExchangeProxy";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "pool",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "tokenInParam",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "tokenOutParam",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxPrice",
            type: "uint256",
          },
        ],
        internalType: "struct ExchangeProxy.Swap[]",
        name: "swaps",
        type: "tuple[]",
      },
      {
        internalType: "address",
        name: "tokenOut",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "minTotalAmountOut",
        type: "uint256",
      },
    ],
    name: "batchEthInSwapExactIn",
    outputs: [
      {
        internalType: "uint256",
        name: "totalAmountOut",
        type: "uint256",
      },
    ],
    payable: true,
    stateMutability: "payable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "pool",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "tokenInParam",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "tokenOutParam",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxPrice",
            type: "uint256",
          },
        ],
        internalType: "struct ExchangeProxy.Swap[]",
        name: "swaps",
        type: "tuple[]",
      },
      {
        internalType: "address",
        name: "tokenOut",
        type: "address",
      },
    ],
    name: "batchEthInSwapExactOut",
    outputs: [
      {
        internalType: "uint256",
        name: "totalAmountIn",
        type: "uint256",
      },
    ],
    payable: true,
    stateMutability: "payable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "pool",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "tokenInParam",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "tokenOutParam",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxPrice",
            type: "uint256",
          },
        ],
        internalType: "struct ExchangeProxy.Swap[]",
        name: "swaps",
        type: "tuple[]",
      },
      {
        internalType: "address",
        name: "tokenIn",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "totalAmountIn",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minTotalAmountOut",
        type: "uint256",
      },
    ],
    name: "batchEthOutSwapExactIn",
    outputs: [
      {
        internalType: "uint256",
        name: "totalAmountOut",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "pool",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "tokenInParam",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "tokenOutParam",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxPrice",
            type: "uint256",
          },
        ],
        internalType: "struct ExchangeProxy.Swap[]",
        name: "swaps",
        type: "tuple[]",
      },
      {
        internalType: "address",
        name: "tokenIn",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "maxTotalAmountIn",
        type: "uint256",
      },
    ],
    name: "batchEthOutSwapExactOut",
    outputs: [
      {
        internalType: "uint256",
        name: "totalAmountIn",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "pool",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "tokenInParam",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "tokenOutParam",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxPrice",
            type: "uint256",
          },
        ],
        internalType: "struct ExchangeProxy.Swap[]",
        name: "swaps",
        type: "tuple[]",
      },
      {
        internalType: "address",
        name: "tokenIn",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenOut",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "totalAmountIn",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minTotalAmountOut",
        type: "uint256",
      },
    ],
    name: "batchSwapExactIn",
    outputs: [
      {
        internalType: "uint256",
        name: "totalAmountOut",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "pool",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "tokenInParam",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "tokenOutParam",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxPrice",
            type: "uint256",
          },
        ],
        internalType: "struct ExchangeProxy.Swap[]",
        name: "swaps",
        type: "tuple[]",
      },
      {
        internalType: "address",
        name: "tokenIn",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenOut",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "maxTotalAmountIn",
        type: "uint256",
      },
    ],
    name: "batchSwapExactOut",
    outputs: [
      {
        internalType: "uint256",
        name: "totalAmountIn",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ExchangeProxy__factory {
  static readonly abi = _abi;
  static createInterface(): ExchangeProxyInterface {
    return new utils.Interface(_abi) as ExchangeProxyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ExchangeProxy {
    return new Contract(address, _abi, signerOrProvider) as ExchangeProxy;
  }
}
