/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "AccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccessControl__factory>;
    getContractFactory(
      name: "IAccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAccessControl__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "BFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BFactory__factory>;
    getContractFactory(
      name: "BPool",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BPool__factory>;
    getContractFactory(
      name: "ExchangeProxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ExchangeProxy__factory>;
    getContractFactory(
      name: "CurveFiOperator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CurveFiOperator__factory>;
    getContractFactory(
      name: "ICurveFiPool",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICurveFiPool__factory>;
    getContractFactory(
      name: "IERC20Modified",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Modified__factory>;

    getContractAt(
      name: "AccessControl",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AccessControl>;
    getContractAt(
      name: "IAccessControl",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IAccessControl>;
    getContractAt(
      name: "ERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "ERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165>;
    getContractAt(
      name: "IERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "BFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BFactory>;
    getContractAt(
      name: "BPool",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BPool>;
    getContractAt(
      name: "ExchangeProxy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ExchangeProxy>;
    getContractAt(
      name: "CurveFiOperator",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CurveFiOperator>;
    getContractAt(
      name: "ICurveFiPool",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ICurveFiPool>;
    getContractAt(
      name: "IERC20Modified",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Modified>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
